#!/usr/bin/env python3

import json
from os import chdir, getcwd, makedirs, rename
from os.path import exists, join
from shutil import copytree
from subprocess import PIPE, run, STDOUT
from sys import exit

def required_file_test(path, root='submission'):
    file_exists = exists(join(root, path))
    return {
        'name': f'Required file {path} present?',
        'status': 'success' if file_exists else 'failed',
        'output': '' if file_exists else f'{path} not found at: {root}'
    }

################################################################################

required_tests = [
    required_file_test('Counter.java', root='submission'),
]

all_required_tests_pass = all([t['status'] == 'success' for t in required_tests])

output = {
    'score': 1.0 if all_required_tests_pass else 0.0,
    'tests': required_tests
}

with open(join('results', 'results.json'), 'w') as f:
    f.write(json.dumps(output))
